source 'https://github.com/noughts/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'NNPanGestureDismissableViewControllerEngine_Example', :exclusive => true do
  pod "NNPanGestureDismissableViewControllerEngine", :path => "../"
  pod "NBULog"
end

target 'NNPanGestureDismissableViewControllerEngine_Tests', :exclusive => true do
  pod "NNPanGestureDismissableViewControllerEngine", :path => "../"

  
end
